version: '3'
services:
  web:
    build: web/
    ports:
     - "5000:5000"
    volumes:
     - ./web/:/code
  redis:
    build: redis/
    ports:
      - "6379:6379"
    volumes:
    - ./redis/store:/data
