version: '3'
services:
  web:
    build: python/
    ports:
     - "5000:5000"
    volumes:
     - ./python/:/code
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    - ./redis/store:/data
